// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tensor_shape.proto

package framework

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Dimensions of a tensor.
type TensorShapeProto struct {
	// Dimensions of the tensor, such as {"input", 30}, {"output", 40}
	// for a 30 x 40 2D tensor.  If an entry has size -1, this
	// corresponds to a dimension of unknown size. The names are
	// optional.
	//
	// The order of entries in "dim" matters: It indicates the layout of the
	// values in the tensor in-memory representation.
	//
	// The first entry in "dim" is the outermost dimension used to layout the
	// values, the last entry is the innermost dimension.  This matches the
	// in-memory layout of RowMajor Eigen tensors.
	//
	// If "dim.size()" > 0, "unknown_rank" must be false.
	Dim []*TensorShapeProto_Dim `protobuf:"bytes,2,rep,name=dim,proto3" json:"dim,omitempty"`
	// If true, the number of dimensions in the shape is unknown.
	//
	// If true, "dim.size()" must be 0.
	UnknownRank          bool     `protobuf:"varint,3,opt,name=unknown_rank,json=unknownRank,proto3" json:"unknown_rank,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TensorShapeProto) Reset()         { *m = TensorShapeProto{} }
func (m *TensorShapeProto) String() string { return proto.CompactTextString(m) }
func (*TensorShapeProto) ProtoMessage()    {}
func (*TensorShapeProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_b204b86f2894c4f2, []int{0}
}

func (m *TensorShapeProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TensorShapeProto.Unmarshal(m, b)
}
func (m *TensorShapeProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TensorShapeProto.Marshal(b, m, deterministic)
}
func (m *TensorShapeProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TensorShapeProto.Merge(m, src)
}
func (m *TensorShapeProto) XXX_Size() int {
	return xxx_messageInfo_TensorShapeProto.Size(m)
}
func (m *TensorShapeProto) XXX_DiscardUnknown() {
	xxx_messageInfo_TensorShapeProto.DiscardUnknown(m)
}

var xxx_messageInfo_TensorShapeProto proto.InternalMessageInfo

func (m *TensorShapeProto) GetDim() []*TensorShapeProto_Dim {
	if m != nil {
		return m.Dim
	}
	return nil
}

func (m *TensorShapeProto) GetUnknownRank() bool {
	if m != nil {
		return m.UnknownRank
	}
	return false
}

// One dimension of the tensor.
type TensorShapeProto_Dim struct {
	// Size of the tensor in that dimension.
	// This value must be >= -1, but values of -1 are reserved for "unknown"
	// shapes (values of -1 mean "unknown" dimension).  Certain wrappers
	// that work with TensorShapeProto may fail at runtime when deserializing
	// a TensorShapeProto containing a dim value of -1.
	Size int64 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	// Optional name of the tensor dimension.
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TensorShapeProto_Dim) Reset()         { *m = TensorShapeProto_Dim{} }
func (m *TensorShapeProto_Dim) String() string { return proto.CompactTextString(m) }
func (*TensorShapeProto_Dim) ProtoMessage()    {}
func (*TensorShapeProto_Dim) Descriptor() ([]byte, []int) {
	return fileDescriptor_b204b86f2894c4f2, []int{0, 0}
}

func (m *TensorShapeProto_Dim) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TensorShapeProto_Dim.Unmarshal(m, b)
}
func (m *TensorShapeProto_Dim) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TensorShapeProto_Dim.Marshal(b, m, deterministic)
}
func (m *TensorShapeProto_Dim) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TensorShapeProto_Dim.Merge(m, src)
}
func (m *TensorShapeProto_Dim) XXX_Size() int {
	return xxx_messageInfo_TensorShapeProto_Dim.Size(m)
}
func (m *TensorShapeProto_Dim) XXX_DiscardUnknown() {
	xxx_messageInfo_TensorShapeProto_Dim.DiscardUnknown(m)
}

var xxx_messageInfo_TensorShapeProto_Dim proto.InternalMessageInfo

func (m *TensorShapeProto_Dim) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *TensorShapeProto_Dim) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*TensorShapeProto)(nil), "tensorflow.TensorShapeProto")
	proto.RegisterType((*TensorShapeProto_Dim)(nil), "tensorflow.TensorShapeProto.Dim")
}

func init() { proto.RegisterFile("tensor_shape.proto", fileDescriptor_b204b86f2894c4f2) }

var fileDescriptor_b204b86f2894c4f2 = []byte{
	// 224 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8f, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0x99, 0x46, 0x44, 0xa7, 0x1e, 0x34, 0xa7, 0xe0, 0x29, 0x7a, 0x71, 0x2f, 0x66, 0xa1,
	0xbe, 0x41, 0xe9, 0x03, 0x94, 0xe8, 0x49, 0x0f, 0x25, 0xd5, 0xec, 0x36, 0x6c, 0x33, 0x53, 0xb2,
	0x29, 0x0b, 0x3e, 0x89, 0x8f, 0xea, 0x51, 0x36, 0x8a, 0xca, 0xde, 0xfe, 0xf9, 0xf8, 0x86, 0x99,
	0x1f, 0x65, 0xf6, 0xd4, 0x73, 0xda, 0xf4, 0x3b, 0x77, 0xf0, 0xe6, 0x90, 0x38, 0xb3, 0xc4, 0x6f,
	0xd6, 0xec, 0x79, 0xb8, 0xfd, 0x00, 0xbc, 0x7c, 0x2a, 0xe3, 0xe3, 0x68, 0xac, 0x8b, 0xb0, 0x40,
	0xf1, 0x16, 0xa2, 0x9a, 0x69, 0x51, 0xcd, 0x17, 0xda, 0xfc, 0xe9, 0x66, 0xaa, 0x9a, 0x55, 0x88,
	0x76, 0x94, 0xe5, 0x0d, 0x5e, 0x1c, 0xa9, 0x23, 0x1e, 0x68, 0x93, 0x1c, 0x75, 0x4a, 0x68, 0xa8,
	0xce, 0xec, 0xfc, 0x87, 0x59, 0x47, 0xdd, 0xf5, 0x3d, 0x8a, 0x55, 0x88, 0x52, 0xe2, 0x49, 0x1f,
	0xde, 0xbd, 0x02, 0x0d, 0x95, 0xb0, 0x25, 0x8f, 0x8c, 0x5c, 0xf4, 0x6a, 0xa6, 0xa1, 0x3a, 0xb7,
	0x25, 0x2f, 0x5f, 0x50, 0x71, 0x6a, 0xff, 0x5f, 0x6f, 0x92, 0x8b, 0x7e, 0xe0, 0xd4, 0x2d, 0xaf,
	0xa6, 0x8f, 0xf4, 0x6b, 0x78, 0xbe, 0x6b, 0x43, 0xde, 0x1d, 0xb7, 0xe6, 0x95, 0x63, 0xdd, 0xba,
	0xbd, 0x67, 0xf2, 0x75, 0x6e, 0x5a, 0xae, 0x4b, 0xed, 0xfa, 0x77, 0xfb, 0x13, 0x60, 0x7b, 0x5a,
	0xd8, 0xc3, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x11, 0x79, 0x5d, 0x2b, 0x20, 0x01, 0x00, 0x00,
}
