// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example_parser_configuration.proto

package example // import "github.com/galeone/tfgo/core/example"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import framework "github.com/galeone/tfgo/core/framework"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type VarLenFeatureProto struct {
	Dtype                   framework.DataType `protobuf:"varint,1,opt,name=dtype,proto3,enum=tensorflow.DataType" json:"dtype,omitempty"`
	ValuesOutputTensorName  string             `protobuf:"bytes,2,opt,name=values_output_tensor_name,json=valuesOutputTensorName,proto3" json:"values_output_tensor_name,omitempty"`
	IndicesOutputTensorName string             `protobuf:"bytes,3,opt,name=indices_output_tensor_name,json=indicesOutputTensorName,proto3" json:"indices_output_tensor_name,omitempty"`
	ShapesOutputTensorName  string             `protobuf:"bytes,4,opt,name=shapes_output_tensor_name,json=shapesOutputTensorName,proto3" json:"shapes_output_tensor_name,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}           `json:"-"`
	XXX_unrecognized        []byte             `json:"-"`
	XXX_sizecache           int32              `json:"-"`
}

func (m *VarLenFeatureProto) Reset()         { *m = VarLenFeatureProto{} }
func (m *VarLenFeatureProto) String() string { return proto.CompactTextString(m) }
func (*VarLenFeatureProto) ProtoMessage()    {}
func (*VarLenFeatureProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_example_parser_configuration_5eb6862a6ac87666, []int{0}
}
func (m *VarLenFeatureProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VarLenFeatureProto.Unmarshal(m, b)
}
func (m *VarLenFeatureProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VarLenFeatureProto.Marshal(b, m, deterministic)
}
func (dst *VarLenFeatureProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VarLenFeatureProto.Merge(dst, src)
}
func (m *VarLenFeatureProto) XXX_Size() int {
	return xxx_messageInfo_VarLenFeatureProto.Size(m)
}
func (m *VarLenFeatureProto) XXX_DiscardUnknown() {
	xxx_messageInfo_VarLenFeatureProto.DiscardUnknown(m)
}

var xxx_messageInfo_VarLenFeatureProto proto.InternalMessageInfo

func (m *VarLenFeatureProto) GetDtype() framework.DataType {
	if m != nil {
		return m.Dtype
	}
	return framework.DataType_DT_INVALID
}

func (m *VarLenFeatureProto) GetValuesOutputTensorName() string {
	if m != nil {
		return m.ValuesOutputTensorName
	}
	return ""
}

func (m *VarLenFeatureProto) GetIndicesOutputTensorName() string {
	if m != nil {
		return m.IndicesOutputTensorName
	}
	return ""
}

func (m *VarLenFeatureProto) GetShapesOutputTensorName() string {
	if m != nil {
		return m.ShapesOutputTensorName
	}
	return ""
}

type FixedLenFeatureProto struct {
	Dtype                  framework.DataType          `protobuf:"varint,1,opt,name=dtype,proto3,enum=tensorflow.DataType" json:"dtype,omitempty"`
	Shape                  *framework.TensorShapeProto `protobuf:"bytes,2,opt,name=shape,proto3" json:"shape,omitempty"`
	DefaultValue           *framework.TensorProto      `protobuf:"bytes,3,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	ValuesOutputTensorName string                      `protobuf:"bytes,4,opt,name=values_output_tensor_name,json=valuesOutputTensorName,proto3" json:"values_output_tensor_name,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}                    `json:"-"`
	XXX_unrecognized       []byte                      `json:"-"`
	XXX_sizecache          int32                       `json:"-"`
}

func (m *FixedLenFeatureProto) Reset()         { *m = FixedLenFeatureProto{} }
func (m *FixedLenFeatureProto) String() string { return proto.CompactTextString(m) }
func (*FixedLenFeatureProto) ProtoMessage()    {}
func (*FixedLenFeatureProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_example_parser_configuration_5eb6862a6ac87666, []int{1}
}
func (m *FixedLenFeatureProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FixedLenFeatureProto.Unmarshal(m, b)
}
func (m *FixedLenFeatureProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FixedLenFeatureProto.Marshal(b, m, deterministic)
}
func (dst *FixedLenFeatureProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FixedLenFeatureProto.Merge(dst, src)
}
func (m *FixedLenFeatureProto) XXX_Size() int {
	return xxx_messageInfo_FixedLenFeatureProto.Size(m)
}
func (m *FixedLenFeatureProto) XXX_DiscardUnknown() {
	xxx_messageInfo_FixedLenFeatureProto.DiscardUnknown(m)
}

var xxx_messageInfo_FixedLenFeatureProto proto.InternalMessageInfo

func (m *FixedLenFeatureProto) GetDtype() framework.DataType {
	if m != nil {
		return m.Dtype
	}
	return framework.DataType_DT_INVALID
}

func (m *FixedLenFeatureProto) GetShape() *framework.TensorShapeProto {
	if m != nil {
		return m.Shape
	}
	return nil
}

func (m *FixedLenFeatureProto) GetDefaultValue() *framework.TensorProto {
	if m != nil {
		return m.DefaultValue
	}
	return nil
}

func (m *FixedLenFeatureProto) GetValuesOutputTensorName() string {
	if m != nil {
		return m.ValuesOutputTensorName
	}
	return ""
}

type FeatureConfiguration struct {
	// Types that are valid to be assigned to Config:
	//	*FeatureConfiguration_FixedLenFeature
	//	*FeatureConfiguration_VarLenFeature
	Config               isFeatureConfiguration_Config `protobuf_oneof:"config"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *FeatureConfiguration) Reset()         { *m = FeatureConfiguration{} }
func (m *FeatureConfiguration) String() string { return proto.CompactTextString(m) }
func (*FeatureConfiguration) ProtoMessage()    {}
func (*FeatureConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_example_parser_configuration_5eb6862a6ac87666, []int{2}
}
func (m *FeatureConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeatureConfiguration.Unmarshal(m, b)
}
func (m *FeatureConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeatureConfiguration.Marshal(b, m, deterministic)
}
func (dst *FeatureConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeatureConfiguration.Merge(dst, src)
}
func (m *FeatureConfiguration) XXX_Size() int {
	return xxx_messageInfo_FeatureConfiguration.Size(m)
}
func (m *FeatureConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_FeatureConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_FeatureConfiguration proto.InternalMessageInfo

type isFeatureConfiguration_Config interface {
	isFeatureConfiguration_Config()
}

type FeatureConfiguration_FixedLenFeature struct {
	FixedLenFeature *FixedLenFeatureProto `protobuf:"bytes,1,opt,name=fixed_len_feature,json=fixedLenFeature,proto3,oneof"`
}
type FeatureConfiguration_VarLenFeature struct {
	VarLenFeature *VarLenFeatureProto `protobuf:"bytes,2,opt,name=var_len_feature,json=varLenFeature,proto3,oneof"`
}

func (*FeatureConfiguration_FixedLenFeature) isFeatureConfiguration_Config() {}
func (*FeatureConfiguration_VarLenFeature) isFeatureConfiguration_Config()   {}

func (m *FeatureConfiguration) GetConfig() isFeatureConfiguration_Config {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *FeatureConfiguration) GetFixedLenFeature() *FixedLenFeatureProto {
	if x, ok := m.GetConfig().(*FeatureConfiguration_FixedLenFeature); ok {
		return x.FixedLenFeature
	}
	return nil
}

func (m *FeatureConfiguration) GetVarLenFeature() *VarLenFeatureProto {
	if x, ok := m.GetConfig().(*FeatureConfiguration_VarLenFeature); ok {
		return x.VarLenFeature
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*FeatureConfiguration) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _FeatureConfiguration_OneofMarshaler, _FeatureConfiguration_OneofUnmarshaler, _FeatureConfiguration_OneofSizer, []interface{}{
		(*FeatureConfiguration_FixedLenFeature)(nil),
		(*FeatureConfiguration_VarLenFeature)(nil),
	}
}

func _FeatureConfiguration_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*FeatureConfiguration)
	// config
	switch x := m.Config.(type) {
	case *FeatureConfiguration_FixedLenFeature:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.FixedLenFeature); err != nil {
			return err
		}
	case *FeatureConfiguration_VarLenFeature:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.VarLenFeature); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("FeatureConfiguration.Config has unexpected type %T", x)
	}
	return nil
}

func _FeatureConfiguration_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*FeatureConfiguration)
	switch tag {
	case 1: // config.fixed_len_feature
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(FixedLenFeatureProto)
		err := b.DecodeMessage(msg)
		m.Config = &FeatureConfiguration_FixedLenFeature{msg}
		return true, err
	case 2: // config.var_len_feature
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(VarLenFeatureProto)
		err := b.DecodeMessage(msg)
		m.Config = &FeatureConfiguration_VarLenFeature{msg}
		return true, err
	default:
		return false, nil
	}
}

func _FeatureConfiguration_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*FeatureConfiguration)
	// config
	switch x := m.Config.(type) {
	case *FeatureConfiguration_FixedLenFeature:
		s := proto.Size(x.FixedLenFeature)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *FeatureConfiguration_VarLenFeature:
		s := proto.Size(x.VarLenFeature)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type ExampleParserConfiguration struct {
	FeatureMap           map[string]*FeatureConfiguration `protobuf:"bytes,1,rep,name=feature_map,json=featureMap,proto3" json:"feature_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *ExampleParserConfiguration) Reset()         { *m = ExampleParserConfiguration{} }
func (m *ExampleParserConfiguration) String() string { return proto.CompactTextString(m) }
func (*ExampleParserConfiguration) ProtoMessage()    {}
func (*ExampleParserConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_example_parser_configuration_5eb6862a6ac87666, []int{3}
}
func (m *ExampleParserConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExampleParserConfiguration.Unmarshal(m, b)
}
func (m *ExampleParserConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExampleParserConfiguration.Marshal(b, m, deterministic)
}
func (dst *ExampleParserConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExampleParserConfiguration.Merge(dst, src)
}
func (m *ExampleParserConfiguration) XXX_Size() int {
	return xxx_messageInfo_ExampleParserConfiguration.Size(m)
}
func (m *ExampleParserConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_ExampleParserConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_ExampleParserConfiguration proto.InternalMessageInfo

func (m *ExampleParserConfiguration) GetFeatureMap() map[string]*FeatureConfiguration {
	if m != nil {
		return m.FeatureMap
	}
	return nil
}

func init() {
	proto.RegisterType((*VarLenFeatureProto)(nil), "tensorflow.VarLenFeatureProto")
	proto.RegisterType((*FixedLenFeatureProto)(nil), "tensorflow.FixedLenFeatureProto")
	proto.RegisterType((*FeatureConfiguration)(nil), "tensorflow.FeatureConfiguration")
	proto.RegisterType((*ExampleParserConfiguration)(nil), "tensorflow.ExampleParserConfiguration")
	proto.RegisterMapType((map[string]*FeatureConfiguration)(nil), "tensorflow.ExampleParserConfiguration.FeatureMapEntry")
}

func init() {
	proto.RegisterFile("example_parser_configuration.proto", fileDescriptor_example_parser_configuration_5eb6862a6ac87666)
}

var fileDescriptor_example_parser_configuration_5eb6862a6ac87666 = []byte{
	// 495 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0xed, 0x26, 0x4d, 0x45, 0xc7, 0x2d, 0x81, 0x55, 0xd5, 0xa6, 0x16, 0x42, 0x96, 0xc5, 0x21,
	0xe2, 0xe0, 0x48, 0x46, 0xaa, 0x28, 0x70, 0x0a, 0xb4, 0xca, 0x01, 0x4a, 0x64, 0xaa, 0x22, 0x71,
	0x59, 0x6d, 0x93, 0xb1, 0x6b, 0x61, 0x7b, 0xad, 0xf5, 0x3a, 0x34, 0xbf, 0xc6, 0x87, 0xf0, 0x1b,
	0x1c, 0xb8, 0x70, 0x44, 0xde, 0xb5, 0xc0, 0x69, 0xdc, 0x5c, 0xb8, 0x79, 0x67, 0xde, 0x9b, 0xb7,
	0xef, 0x79, 0x07, 0x5c, 0xbc, 0xe5, 0x69, 0x9e, 0x20, 0xcb, 0xb9, 0x2c, 0x50, 0xb2, 0x99, 0xc8,
	0xc2, 0x38, 0x2a, 0x25, 0x57, 0xb1, 0xc8, 0xbc, 0x5c, 0x0a, 0x25, 0x28, 0x28, 0xcc, 0x0a, 0x21,
	0xc3, 0x44, 0x7c, 0xb3, 0xa9, 0xf9, 0x66, 0xc5, 0x0d, 0xcf, 0xd1, 0xf4, 0xed, 0x3d, 0x53, 0xab,
	0x4f, 0x96, 0x5a, 0xe6, 0x58, 0x98, 0x83, 0xfb, 0x8b, 0x00, 0xbd, 0xe2, 0xf2, 0x3d, 0x66, 0xe7,
	0xc8, 0x55, 0x29, 0x71, 0xaa, 0x27, 0x3e, 0x87, 0xde, 0xbc, 0x82, 0x0d, 0x88, 0x43, 0x86, 0x0f,
	0xfd, 0x03, 0xef, 0x9f, 0x82, 0xf7, 0x8e, 0x2b, 0x7e, 0xb9, 0xcc, 0x31, 0x30, 0x10, 0x7a, 0x0a,
	0xc7, 0x0b, 0x9e, 0x94, 0x58, 0x30, 0x51, 0xaa, 0xbc, 0x54, 0xac, 0xbe, 0x41, 0xc6, 0x53, 0x1c,
	0x74, 0x1c, 0x32, 0xdc, 0x0d, 0x0e, 0x0d, 0xe0, 0xa3, 0xee, 0x5f, 0xea, 0xf6, 0x05, 0x4f, 0x91,
	0xbe, 0x06, 0x3b, 0xce, 0xe6, 0xf1, 0xac, 0x9d, 0xdb, 0xd5, 0xdc, 0xa3, 0x1a, 0xb1, 0x46, 0x3e,
	0x85, 0x63, 0x6d, 0xb2, 0x95, 0xbb, 0x6d, 0x74, 0x0d, 0xe0, 0x2e, 0xd5, 0xfd, 0x49, 0xe0, 0xe0,
	0x3c, 0xbe, 0xc5, 0xf9, 0xff, 0xf8, 0xf6, 0xa1, 0xa7, 0xc7, 0x6b, 0x8f, 0x96, 0xff, 0xa4, 0x89,
	0x35, 0x5a, 0x9f, 0xaa, 0xb6, 0x1e, 0x1c, 0x18, 0x28, 0x7d, 0x03, 0xfb, 0x73, 0x0c, 0x79, 0x99,
	0x28, 0xa6, 0x23, 0xd1, 0x1e, 0x2d, 0xff, 0x68, 0x9d, 0x6b, 0x68, 0x7b, 0x35, 0xfa, 0xaa, 0x02,
	0x6f, 0x4e, 0x7a, 0x7b, 0x53, 0xd2, 0xee, 0xf7, 0xca, 0xb1, 0x71, 0xfa, 0xb6, 0xf9, 0x82, 0xe8,
	0x05, 0x3c, 0x0e, 0xab, 0x24, 0x58, 0x82, 0x19, 0x0b, 0x0d, 0x42, 0xbb, 0xb7, 0x7c, 0xa7, 0x79,
	0xab, 0xb6, 0xb8, 0x26, 0x5b, 0x41, 0x3f, 0x5c, 0xad, 0xd3, 0x09, 0xf4, 0x17, 0x5c, 0xae, 0x4c,
	0x33, 0xf9, 0x3c, 0x6d, 0x4e, 0x5b, 0x7f, 0x72, 0x93, 0xad, 0x60, 0x7f, 0xd1, 0xac, 0x8e, 0x1f,
	0xc0, 0x8e, 0x79, 0xec, 0xee, 0x0f, 0x02, 0xf6, 0x99, 0x59, 0x83, 0xa9, 0xde, 0x82, 0x55, 0x0b,
	0x9f, 0xc1, 0xaa, 0xa5, 0x58, 0xca, 0xf3, 0x01, 0x71, 0xba, 0x43, 0xcb, 0x3f, 0x69, 0xca, 0xdd,
	0x4f, 0xf6, 0x6a, 0xb5, 0x0f, 0x3c, 0x3f, 0xcb, 0x94, 0x5c, 0x06, 0x10, 0xfe, 0x2d, 0xd8, 0x0c,
	0xfa, 0x77, 0xda, 0xf4, 0x11, 0x74, 0xbf, 0xe2, 0x52, 0x07, 0xb4, 0x1b, 0x54, 0x9f, 0xf4, 0x04,
	0x7a, 0xe6, 0x57, 0x76, 0x5a, 0x42, 0x6b, 0x49, 0x3c, 0x30, 0xf0, 0x57, 0x9d, 0x97, 0x64, 0x8c,
	0x70, 0x28, 0x64, 0xd4, 0x64, 0xd4, 0xdb, 0x3e, 0x76, 0xee, 0xbf, 0xb2, 0x8e, 0xab, 0x98, 0x92,
	0x2f, 0xcf, 0xa2, 0x58, 0xdd, 0x94, 0xd7, 0xde, 0x4c, 0xa4, 0xa3, 0x88, 0x27, 0x28, 0x32, 0x1c,
	0xa9, 0x30, 0x12, 0xa3, 0x99, 0x90, 0x38, 0xaa, 0x27, 0xfd, 0x26, 0xe4, 0x7a, 0x47, 0xef, 0xfa,
	0x8b, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x30, 0x94, 0x9d, 0x2f, 0x4c, 0x04, 0x00, 0x00,
}
